// flow-typed signature: d45148b4db77c23310170e5c4f7de937
// flow-typed version: <<STUB>>/eslint-config-samsao-web_v^1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-samsao-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-samsao-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-samsao-web/rules/env' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-web/rules/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-samsao-web/index' {
  declare module.exports: $Exports<'eslint-config-samsao-web'>;
}
declare module 'eslint-config-samsao-web/index.js' {
  declare module.exports: $Exports<'eslint-config-samsao-web'>;
}
declare module 'eslint-config-samsao-web/rules/env.js' {
  declare module.exports: $Exports<'eslint-config-samsao-web/rules/env'>;
}
declare module 'eslint-config-samsao-web/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-samsao-web/rules/react'>;
}
