// flow-typed signature: 169c497bfab2a02416f83ac590476715
// flow-typed version: <<STUB>>/eslint-config-samsao-mobile_v^1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-samsao-mobile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-samsao-mobile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-samsao-mobile/rules/react-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-samsao-mobile/index' {
  declare module.exports: $Exports<'eslint-config-samsao-mobile'>;
}
declare module 'eslint-config-samsao-mobile/index.js' {
  declare module.exports: $Exports<'eslint-config-samsao-mobile'>;
}
declare module 'eslint-config-samsao-mobile/rules/react-native.js' {
  declare module.exports: $Exports<'eslint-config-samsao-mobile/rules/react-native'>;
}
