// flow-typed signature: 1efef9f1a1d0b516b934711cd104b323
// flow-typed version: <<STUB>>/object-mapper_v^3.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-mapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-mapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-mapper/src/get-key-value' {
  declare module.exports: any;
}

declare module 'object-mapper/src/object-mapper' {
  declare module.exports: any;
}

declare module 'object-mapper/src/set-key-value' {
  declare module.exports: any;
}

declare module 'object-mapper/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-mapper/index' {
  declare module.exports: $Exports<'object-mapper'>;
}
declare module 'object-mapper/index.js' {
  declare module.exports: $Exports<'object-mapper'>;
}
declare module 'object-mapper/src/get-key-value.js' {
  declare module.exports: $Exports<'object-mapper/src/get-key-value'>;
}
declare module 'object-mapper/src/object-mapper.js' {
  declare module.exports: $Exports<'object-mapper/src/object-mapper'>;
}
declare module 'object-mapper/src/set-key-value.js' {
  declare module.exports: $Exports<'object-mapper/src/set-key-value'>;
}
declare module 'object-mapper/test/test.js' {
  declare module.exports: $Exports<'object-mapper/test/test'>;
}
