export const FETCH_TALKS = 'FETCH_TALKS';
export const SORT_TALKS_BY_DATE = 'SORT_TALKS_BY_DATE';
export const FETCH_TALK_WITH_ID = 'FETCH_TALK_WITH_ID';
export const FETCH_TALKS_FOR_SPEAKER = 'FETCH_TALKS_FOR_SPEAKER';
export const RECEIVED_TALKS = 'RECEIVED_TALKS';
export const FETCH_TALKS_FAILED = 'FETCH_TALKS_FAILED';
export const SELECT_TALK = 'SELECT_TALK';
